import 'package:flutter/material.dart';

import 'app_colors.dart';

const appHeaderStyleLarge = TextStyle(fontSize: 28, fontWeight: FontWeight.w700, color: primaryColor);
const appHeaderStyle = TextStyle(fontSize: 24, fontWeight: FontWeight.w600, color: primaryColor);
const textStyleBlackLarge = TextStyle(fontSize: 18, fontWeight: FontWeight.w500, color: textColorBlack);
const subHeaderStyle = TextStyle(fontSize: 16.0, fontWeight: FontWeight.w500, color: Colors.white);
const appHeaderStyleBlack = TextStyle(fontSize: 24, fontWeight: FontWeight.w600, color: textColorBlack);
const appSubHeaderStyle = TextStyle(fontSize: 18, fontWeight: FontWeight.w400, color: textColorGrey);
const appSubHeaderStyleMediumBold = TextStyle(fontSize: 18, fontWeight: FontWeight.w600, color: textColorGrey);
const appSubHeaderStyleBold = TextStyle(fontSize: 20, fontWeight: FontWeight.w700, color: textColorGrey);
const appSubHeaderStyleBlack= TextStyle(fontSize: 18, fontWeight: FontWeight.w400, color: textColorBlack);
const textStyleStyleBlackSmall= TextStyle(fontSize: 14, fontWeight: FontWeight.w400, color: textColorBlack);
const textStyle = TextStyle(fontSize: 16, fontWeight: FontWeight.w400, color: textColorGrey);
const textStyleBold = TextStyle(fontSize: 16, fontWeight: FontWeight.w500, color: textColorGrey);
const subTextStyle = TextStyle(fontSize: 14, fontWeight: FontWeight.w400, color: textColorGrey);
const textStyleSmall = TextStyle(fontSize: 12, fontWeight: FontWeight.w400, color: textColorGrey);
const textStyleWhite = TextStyle(fontSize: 18, fontWeight: FontWeight.w400, color: Colors.white);
const titleStyleWhiteLight = TextStyle(fontSize: 18.0, fontWeight: FontWeight.w400, color: Colors.white);
const titleStyle = TextStyle(fontSize: 16.0, fontWeight: FontWeight.w900, color: textColorDarkBlue);
const textStyleWhiteLight = TextStyle(fontSize: 16, fontWeight: FontWeight.w400, color: Colors.white);
const titleStyleWhite = TextStyle(fontSize: 18.0, fontWeight: FontWeight.w700, color: Colors.white);
const textStylePrimary = TextStyle(fontSize: 16, fontWeight: FontWeight.w400, color: primaryColor);
const textStyleWhiteSmall = TextStyle(fontSize: 12, fontWeight: FontWeight.w400, color: Colors.white);
const errorStyleRed = TextStyle(fontSize: 16, fontWeight: FontWeight.w500, color: textColorRed);
const textStyleRed = TextStyle(fontSize: 18, fontWeight: FontWeight.w500, color: textColorRed);
const appSubHeaderStyleBlacks= TextStyle(fontSize: 22, fontWeight: FontWeight.w400, color: textColorBlack);
const appStyleBlack= TextStyle(fontSize: 16, fontWeight: FontWeight.w400, color: textColorBlack);
const appStyleBlacks= TextStyle(fontSize: 18, fontWeight: FontWeight.w400, color: textColorBlack);
const greyText = TextStyle(fontSize: 20.0, color: Colors.black54,fontWeight: FontWeight.bold);
const greyTexts = TextStyle(fontSize: 18.0, color: Colors.black54,fontWeight: FontWeight.bold);
const textStyles = TextStyle(fontSize: 16, fontWeight: FontWeight.w400, color: textColorGrey);
const appHeaderStyles = TextStyle(fontSize: 18, fontWeight: FontWeight.w600, color: textColorBlack);
const appHeaderStyless = TextStyle(fontSize: 18, fontWeight: FontWeight.w600, color: textColorLightBlue);
const blueText = TextStyle(fontSize: 18, color: Colors.blue,fontWeight: FontWeight.bold);
const blueTextSmaller = TextStyle(fontSize: 16, fontWeight: FontWeight.w500, color: Colors.blue);
const appBarTitleStyle = TextStyle(fontSize: 18, color: Colors.white,fontWeight: FontWeight.bold);
const titleBlack = TextStyle(fontSize: 24.0, color: Colors.black54,fontWeight: FontWeight.bold);
const textStyleWhiteLargeBold = TextStyle(fontSize: 18, fontWeight: FontWeight.w500, color: Colors.white);
const textStyleSecondary = TextStyle(fontSize: 16, fontWeight: FontWeight.w500, color: secondaryColor);
const titleStyleLarge = TextStyle(fontSize: 18.0, fontWeight: FontWeight.w700, color: secondaryColor);
const textStylePrimarySmall = TextStyle(fontSize: 14, fontWeight: FontWeight.w400, color: primaryColor);